import { z } from 'zod';
import { EXCALIDRAW_ELEMENT_TYPES, ExcalidrawElementType } from '../types.js';

export const CreateElementSchema = z.object({
  id: z.string().optional(),
  type: z.enum(Object.values(EXCALIDRAW_ELEMENT_TYPES) as [ExcalidrawElementType, ...ExcalidrawElementType[]]),
  x: z.number(),
  y: z.number(),
  width: z.number().optional(),
  height: z.number().optional(),
  backgroundColor: z.string().optional(),
  strokeColor: z.string().optional(),
  strokeWidth: z.number().optional(),
  strokeStyle: z.string().optional(),
  roughness: z.number().optional(),
  opacity: z.number().optional(),
  text: z.string().optional(),
  label: z.object({ text: z.string() }).optional(),
  fontSize: z.number().optional(),
  fontFamily: z.union([z.string(), z.number()]).optional(),
  groupIds: z.array(z.string()).optional(),
  locked: z.boolean().optional(),
  roundness: z.object({ type: z.number(), value: z.number().optional() }).nullable().optional(),
  fillStyle: z.string().optional(),
  points: z.any().optional(),
  start: z.object({ id: z.string() }).optional(),
  end: z.object({ id: z.string() }).optional(),
  startArrowhead: z.string().nullable().optional(),
  endArrowhead: z.string().nullable().optional(),
  elbowed: z.boolean().optional(),
  startBinding: z.object({
    elementId: z.string(), focus: z.number().optional(), gap: z.number().optional(),
    fixedPoint: z.tuple([z.number(), z.number()]).nullable().optional(), mode: z.string().optional(),
  }).nullable().optional(),
  endBinding: z.object({
    elementId: z.string(), focus: z.number().optional(), gap: z.number().optional(),
    fixedPoint: z.tuple([z.number(), z.number()]).nullable().optional(), mode: z.string().optional(),
  }).nullable().optional(),
  boundElements: z.array(z.object({ id: z.string(), type: z.enum(['arrow', 'text']) })).nullable().optional(),
  fileId: z.string().optional(),
  status: z.string().optional(),
  scale: z.tuple([z.number(), z.number()]).optional(),
});

export const UpdateElementSchema = z.object({
  id: z.string(),
  type: z.enum(Object.values(EXCALIDRAW_ELEMENT_TYPES) as [ExcalidrawElementType, ...ExcalidrawElementType[]]).optional(),
  x: z.number().optional(),
  y: z.number().optional(),
  width: z.number().optional(),
  height: z.number().optional(),
  backgroundColor: z.string().optional(),
  strokeColor: z.string().optional(),
  strokeWidth: z.number().optional(),
  strokeStyle: z.string().optional(),
  roughness: z.number().optional(),
  opacity: z.number().optional(),
  text: z.string().optional(),
  originalText: z.string().optional(),
  label: z.object({ text: z.string() }).optional(),
  fontSize: z.number().optional(),
  fontFamily: z.union([z.string(), z.number()]).optional(),
  groupIds: z.array(z.string()).optional(),
  locked: z.boolean().optional(),
  roundness: z.object({ type: z.number(), value: z.number().optional() }).nullable().optional(),
  fillStyle: z.string().optional(),
  points: z.array(z.union([
    z.tuple([z.number(), z.number()]),
    z.object({ x: z.number(), y: z.number() })
  ])).optional(),
  start: z.object({ id: z.string() }).optional(),
  end: z.object({ id: z.string() }).optional(),
  startArrowhead: z.string().nullable().optional(),
  endArrowhead: z.string().nullable().optional(),
  elbowed: z.boolean().optional(),
  startBinding: z.object({
    elementId: z.string(), focus: z.number().optional(), gap: z.number().optional(),
    fixedPoint: z.tuple([z.number(), z.number()]).nullable().optional(), mode: z.string().optional(),
  }).nullable().optional(),
  endBinding: z.object({
    elementId: z.string(), focus: z.number().optional(), gap: z.number().optional(),
    fixedPoint: z.tuple([z.number(), z.number()]).nullable().optional(), mode: z.string().optional(),
  }).nullable().optional(),
  boundElements: z.array(z.object({ id: z.string(), type: z.enum(['arrow', 'text']) })).nullable().optional(),
  fileId: z.string().optional(),
  status: z.string().optional(),
  scale: z.tuple([z.number(), z.number()]).optional(),
});
